### ISSUE TITLE
No Hits

### ISSUE THREAD

**Issue by bibilujan** [DRL/blobtools#18]
Hi, 

I am interested in running this tool to possibly visualize and pull out some symbionts from my sample. I was able to use bloobtools to and get the graph and table with view and blobplot commands, but I get all my entries as "no hits". Would you be able to help me to troubleshoot this issue? My assembly is of a 260MB plant, closely related to A. thaliana so there should be lots of hits that are properly annotated. 

Here is the summary stats:

C.microcarpa-plot-4.C.microcarpa.BlobDB.json.span.phylum.p7.100.bestsum - spades
Group	colour	count	visible (%)	span	visible(%)	n50	GC	GC (std)	cov_mean	cov_std	read map	read map (%)
all	None	49,622	100.0%	203,388,998	100.0%	107,031	0.41	0.1	25.2	172.8	0	0.0%
no-hit	#d3d3d3	49,622	100.0%	203,388,998	100.0%	107,031	0.41	0.1	25.2	172.8	0	0.0%

And a few lines from the "view" output (the last is a hit to A. thaliana):

NODE_1_length_1111123_cov_10.2151_ID_114688196	6429	gi|727511611|ref|XM_010433800.1|	97.47	3795	44	29	708277	712041	3773	1	0.0
NODE_1_length_1111123_cov_10.2151_ID_114688196	5991	gi|727522685|ref|XM_010439039.1|	99.57	3286	14	0	992226	995511	6183903	0.0
NODE_1_length_1111123_cov_10.2151_ID_114688196	5485	gi|727547328|ref|XM_010448413.1|	95.46	3483	80	44	708279	711744	3425	4	0.0
NODE_1_length_1111123_cov_10.2151_ID_114688196	4427	gi|7270623|emb|AL161590.2|	87.72	3958	280	121	708239	712136	166312	170123	0.0

**Comment by DRL** [comment]
Hi bibilujan,

your blast file has to be in the format '6 qseqid staxids bitscore ...', while your blast results seem to be in the format '6 qseqid staxids subject ...'

I recommend re-running the blast with : 

```-outfmt '6 qseqid staxids bitscore std sscinames sskingdoms stitle'```

that should fix the issue

cheers, 

dom

**Comment by bibilujan** [comment]
Hi Dom, 

The results you see I actually got after running the blast in the way you are specifying, here is the command:

blastn -task megablast -query ../Assembly_C.microcarpa/Old_Assemblies/C.microcarpa-m13c-filtered-200.fasta -db nt-ref-db/nt -outfmt '6 qseqid staxids bitscore std sscinames sskingdoms stitle' -max_target_seqs 25 -culling_limit 2 -num_threads 16 -evalue 1e-25 -out C.microcarpa13.vs.nt.25cul1.1e25.megablast.out

I deleted the third row from my blast results and re-ran blobplot, and I did get hits this time, however im not sure why this is happening or if I can trust these results. What do you think?

Thank you for taking the time to look at this, 

Beatriz


![c microcarpa-plot c microcarpa blobdb json span phylum p7 100 bestsum blobs spades](https://cloud.githubusercontent.com/assets/6969249/15993501/5f753a7c-30b6-11e6-9e96-7c560eeece75.png)
[C.microcarpa-plot.C.microcarpa.BlobDB.json.span.phylum.p7.100.bestsum.stats.txt](https://github.com/DRL/blobtools/files/310953/C.microcarpa-plot.C.microcarpa.BlobDB.json.span.phylum.p7.100.bestsum.stats.txt)

**Comment by DRL** [comment]
Hi Beatriz, 

nice blobplot! :)

several things:
- the blobplot looks good, in the sense that blobtools could parse taxonomy information from the blast result(s). So in theory everything should be good, although I'd like to check the blastfile myself.
- could you ```tar -zcvf``` your blast result(s) and sent me a dropbox link to it so I can check if there's something wrong there?

Regarding the plot:
- you have lots of proteobacteria in there (which is fine)
- you have ~50 Mb of "undef". That is a result from blast hits to sequences that do not have the taxonomic rank of "phylum" assigned to them (according to NCBI taxonomy). That happens sometimes. You want to check what taxids are causing this and maybe run the blobplot command again on another rank (e.g., order). Maybe these are hitting your target organism, but return "undef" because your target organism might not have a proper taxonomy (in the NCBI taxonomy/nt database you are using)
- You might want to check when your taxonomy/nt database has last been updated

hope this helps,

dom

**Comment by bibilujan** [comment]
Here you can find the blast results, this is before removing the third row:

https://www.dropbox.com/s/l9iwvc3i9wdjulb/C.microcarpa_blast_results.tar?dl=0

Is it common to have so much proteobacteria? I was hoping to find some fungi in there. I did re-download the most recent nt database and taxonomy, because I thought that was why I was not getting any hits initially. 

Thanks, 

Beatriz

**Comment by bibilujan** [comment]
I had placed a damaged file on dropbox, but I have replaced it with the correct one now.

https://www.dropbox.com/s/l9iwvc3i9wdjulb/C.microcarpa_blast_results.tar?dl=0

Thanks, 

Beatriz

**Comment by DRL** [comment]
Hi Beatriz, 

the problem with the blast file is that the second column does not carry the taxid:
- your format is ```qseqid bitscore std ...````

This could be because you are missing the taxonomy database from NCBI and therefor BLAST can not assign a ```taxid``` to the hits. Another possibility is that the ```taxdb``` database is not in the path defined by the BLASTDB environment variable.

cheers, 

dom

**Comment by bibilujan** [comment]
Hi again Dom, 

I have fixed the last problem. Now again blobtools is not parsing the blast output properly and I get all no hits in the plot. Do you see any issues with this format? 

NODE_1_length_1111123_cov_10.2151_ID_114688196	90675	6429	gi|727511611|ref|XM_010433800.1|	97.470	3794	46	26	708277	712041	3773	1	0.0	Camelina sativa	Eukaryota	PREDICTED: Camelina sativa uncharacterized LOC104716425 (LOC104716425), mRNA
NODE_1_length_1111123_cov_10.2151_ID_114688196	90675	5991	gi|727522685|ref|XM_010439039.1|	99.574	3286	14	0	992226	995511	618	3903	0.0	Camelina sativa	Eukaryota	PREDICTED: Camelina sativa auxilin-like protein 1 (LOC104721124), mRNA
NODE_1_length_1111123_cov_10.2151_ID_114688196	90675	1077	gi|727522685|ref|XM_010439039.1|	97.927	627	3	5	991523	992144	1	622	0.0	Camelina sativa	Eukaryota	PREDICTED: Camelina sativa auxilin-like protein 1 (LOC104721124), mRNA

blast command:
blastn -task megablast -query C.microcarpa-m13c-filtered-200.fasta -db nt -outfmt '6 qseqid staxids bitscore std sscinames sskingdoms stitle' -max_target_seqs 25 -culling_limit 2 -evalue 1e-25 -out C.microcarpa13.vs.nt.25cul1.1e25.megablast.out.June17

Thanks, 

Beatriz
