### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by macisz** [DRL/blobtools#61]
Hello, 
I've been trying to run Blobtools a number of times recently, on various sets of input data, and regardless of the input I keep getting the same error, given in the title of this post. More details are shown here:
![blobtools error](https://user-images.githubusercontent.com/32582044/31660831-014ad644-b339-11e7-9084-f60ad73d82b0.jpg)
Is there something wrong with my version of the tools, or are the input files in wrong format somehow? I'm aware that this might be a beginner-level mistake I've made, but I'm a biologist with very little experience with anything related to bioinformatics.
Thanks for your support!
KM

**Comment by DRL** [comment]
Hi KM, 

that sounds like an old bug that has been fixed in the 1.0 version. And I think that only occurred if the BAM file contained no mapping reads, but I could be wrong.

I would recommend to install the current version. And then check whether you BAM file is correct (do the contigs in the FASTA and the contigs in the BAM have the same name? Does the BAM file have mapping reads?) ... 

Let me know if this solves your problem... 

cheers, 

dom

**Comment by macisz** [comment]
Hi,
it seems that what I've been trying to use as the BAM file wasn't exactly a proper BAM at all. It's all working now, thank you very much for your support!
Cheers
KM
