### ISSUE TITLE
Feature Request: Using Kraken for hits

### ISSUE THREAD

**Issue by nickp60** [DRL/blobtools#62]
Hi, I'm not sure if I have missed something, but is there a way to use the output from Kraken as a hits file?  The main thing missing is some way of inferring a score for the third column of the blobtools hits file.  The scope for the Kraken output files are given [here](https://ccb.jhu.edu/software/kraken/MANUAL.html#output-format)

Any advice would be appreciated!

Thanks,

~Nick

**Comment by DRL** [comment]
Hi Nick, 

If you just want the Kraken classification, you could just pick any number for a score (e.g. 100) and then run something like the line below which will take all contigs which were classified by Kraken (and their taxids) and assigns them a score of 100: 

```
 awk '$1=="C"' $KRAKENFILE | cut -f2,3 | perl -ne  'chomp; print $_."\t100\n"'
```

Comments:
- Kraken might not assign taxids at a particular taxonomic rank, so you could see some undef's
- if you also want to add BLAST/Diamond/other results to the same blobdb so that BlobTools processes them with a taxrule, you should choose your "Kraken-score" accordingly.

but should work AFAIK ...

let me know if you have troubles.

cheers, 

dom
