### ISSUE TITLE
Comparing multiple samples using the same color representation of blobs

### ISSUE THREAD

**Issue by Jigyasa3** [DRL/blobtools#75]
Hello

Is it possible to use the same key or color representation of blobs for different samples? When I run blobtools plot command it generates the gc-cov plot but assigns different colors to same taxonomically classified contig. For example, E.coli in one sample is represented by blue whereas in other sample by red.
There is a --color <FILE> option, but could you explain the file format for it?

**Comment by DRL** [comment]
Hi Jigyasa3,

If you look in the examples folder the is a ```colours.txt``` CSV file in the right format, which can be used with the ```--colour``` flag. 

It is essentially composed of two fields (name of the taxonomic group and HEX colour), separated by commas, i.e.:
```
Nematoda,#48a365
Tardigrada,#48a365
Actinobacteria,#926eb3
other,#ffffff
```

In order to use the automatically generated colours by blobtools you can consult the *.stats.txt file generated when making a blobplot. There the different taxonomic groups are listed together with metrics including the HEX colour they were assigned in the blobplot.

Hope that helps,

cheers, 

dom
