### ISSUE TITLE
the output plot is empty

### ISSUE THREAD

**Issue by XClaws** [DRL/blobtools#94]
Dear Team,

I would like to check the contamination of my RNA read data.
Here is how I apply blobtool for my goal:
1. I have sample 10000 RNA reads from 8 different materials from the same organism
2. I assembled a de novo Transcriptome based on these 80,000 RNA reads. (the assembly)
3. then I mapped the RNA reads back to the transcriptome. (the mapping.bam)
4. I blasted the Transcriptome to the ncbi nt database. (the blast.out)
5. run the blobtool protocol

However, I got a weird output plot. Could you please help me to interpret it or tell me whether I applied it wrong or not?

Thank you very much, looking forward to your repsonse.

![Lsal_RNA blobDB json bestsum phylum p8 span 100 blobplot bam0](https://user-images.githubusercontent.com/14818616/66207098-2886c980-e6b2-11e9-8ae4-f79e6c73e971.png)
![Lsal_RNA blobDB json bestsum phylum p8 span 100 blobplot read_cov bam0](https://user-images.githubusercontent.com/14818616/66207105-2de41400-e6b2-11e9-929d-0ee1fc560b40.png)

**Comment by francicco** [comment]
I got the exact same problem. It is because the json file is empty.
F

**Comment by francicco** [comment]
I got the same error, therefore I tested the example provided. There is the exact same result.

![TEST1 blobDB json bestsum phylum p8 span 100 blobplot bam0](https://user-images.githubusercontent.com/9006870/66948709-1cedb800-f04d-11e9-9394-0052750e1a8f.png)
![TEST1 blobDB json bestsum phylum p8 span 100 blobplot read_cov bam0](https://user-images.githubusercontent.com/9006870/66948713-1f501200-f04d-11e9-9846-cd4afeec4aa3.png)

There's something wrong with `blobtools plot`. 

Best
F

**Comment by francicco** [comment]
Ok, I got the problem. I was using python2.7 instead of python3

![Blobtools out blobDB json bestsum phylum p8 span 100 blobplot bam0](https://user-images.githubusercontent.com/9006870/66950970-5294a000-f051-11e9-922b-80b9592b3fd3.png)
![Blobtools out blobDB json bestsum phylum p8 span 100 blobplot read_cov bam0](https://user-images.githubusercontent.com/9006870/66950976-56282700-f051-11e9-8e42-c87a2876db8a.png)

F

**Comment by DRL** [comment]
Hi XClaws,

you have to be aware that blobtools was originally developed for genome datasets and not for transcriptome datasets. The reason is that coverage in genome assemblies is a proxy for molarity of DNA molecules sequenced: DNA of a particular organism will be sequenced at roughly the same coverage, contaminants tend to occur at different coverages, etc ... 

In a transcriptome dataset, coverage is a proxy for molarity of RNA molecules sequenced which is determined by expression levels. 

I am not sure I entirely understand the description of your analysis, but it sounds like you subsampled reads from your RNAseq dataset. That makes no sense and will give you very few assembled contigs. 

Regarding the example dataset not working, use python3 ...

cheers, 

dom

**Comment by XClaws** [comment]
Dear Dom,

Thanks for your explanation!
